export const USER_REGISTER = 'USER_REGISTER';
export const USER_SIGN_IN = 'USER_SIGN_IN';
export const USER_SIGN_OUT = 'USER_SIGN_OUT';

export const ADD_USER_TODO_LIST = 'ADD_USER_TODO_LIST';
export const DELETE_USER_TODO_LIST = 'DELETE_USER_TODO_LIST';
export const UPDATE_USER_TODO_LIST = 'UPDATE_USER_TODO_LIST';
